basePath: /
host: ws-andikamf-8a9eea7e7e50.herokuapp.com
info:
  contact:
    email: andikamusk@gmail.com
    name: API Support
    url: https://github.com/nekowawolf
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
